"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

import dj_database_url  # <- make sure this is installed: pip install dj-database-url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# Security & Debug
# ============================================================

# SECRET_KEY & DEBUG should come from environment variables in production
# For local dev, you can keep default fallback values.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "dev-secret-key-change-me"  # fallback only for local development
)

DEBUG = os.getenv("DEBUG", "True") == "True"

# When you know your Heroku app name, replace 'your-app-name' below
# e.g. 'https://my-django-app-123.herokuapp.com'
CSRF_TRUSTED_ORIGINS = [
    # Add your real Heroku URL here when you know it
    # "https://your-app-name.herokuapp.com",
]

# Allow all hosts for now (simpler when testing). Later you can restrict.
ALLOWED_HOSTS = ["*"]

# ============================================================
# Application definition
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bookings",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise should be right after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Use WhiteNoise's staticfiles storage backend
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # You can add custom template dirs here if needed
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ============================================================
# Database
# ============================================================
# On Heroku, DATABASE_URL is automatically provided.
# Locally, it will fall back to sqlite3.

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,  # You can set True if needed for strict SSL
    )
}

# ============================================================
# Password validation
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================================
# Internationalization
# ============================================================

LANGUAGE_CODE = "th"

TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_TZ = True

# ============================================================
# Static files (CSS, JavaScript, Images)
# ============================================================

STATIC_URL = "static/"

# Folder where collectstatic will put all static files (for Heroku)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Optional: if you have a local "static" folder in your project
# STATICFILES_DIRS = [BASE_DIR / "static"]

# ============================================================
# Default primary key field type
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
