# Generated by Django 5.2.8 on 2025-11-13 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=10, unique=True, verbose_name='เลขที่จอด')),
                ('zone', models.CharField(choices=[('A', 'โซน A - ใกล้ทางเข้า'), ('B', 'โซน B - กลาง'), ('C', 'โซน C - ด้านหลัง')], max_length=1, verbose_name='โซน')),
                ('is_available', models.BooleanField(default=True, verbose_name='ว่าง')),
            ],
            options={
                'verbose_name': 'ที่จอดรถ',
                'verbose_name_plural': 'ที่จอดรถ',
                'ordering': ['zone', 'spot_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='รหัสจอง')),
                ('car_license', models.CharField(max_length=20, verbose_name='ทะเบียนรถ')),
                ('car_model', models.CharField(max_length=100, verbose_name='ยี่ห้อ/รุ่น')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทร')),
                ('booking_date', models.DateField(verbose_name='วันที่จอง')),
                ('start_time', models.TimeField(verbose_name='เวลาเข้า')),
                ('end_time', models.TimeField(verbose_name='เวลาออก')),
                ('status', models.CharField(choices=[('WAITING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธ'), ('CANCELLED', 'ยกเลิก')], default='WAITING', max_length=10, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัพเดตเมื่อ')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='อนุมัติเมื่อ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL, verbose_name='อนุมัติโดย')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.parkingspot', verbose_name='ที่จอดรถ')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='เลขที่ตั๋ว')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR Code')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='ออกตั๋วเมื่อ')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='การจอง')),
            ],
            options={
                'verbose_name': 'ตั๋วจอดรถ',
                'verbose_name_plural': 'ตั๋วจอดรถ',
                'ordering': ['-issued_at'],
            },
        ),
    ]
