# Generated by Django 5.2.8 on 2025-11-13 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_license', models.CharField(max_length=20, verbose_name='ทะเบียนรถ')),
                ('car_model', models.CharField(max_length=100, verbose_name='ยี่ห้อ/รุ่น')),
                ('car_color', models.CharField(blank=True, max_length=50, verbose_name='สีรถ')),
                ('is_default', models.BooleanField(default=False, verbose_name='รถหลัก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เพิ่มเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของ')),
            ],
            options={
                'verbose_name': 'รถยนต์ของผู้ใช้',
                'verbose_name_plural': 'รถยนต์ของผู้ใช้',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'car_license')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='user_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.usercar', verbose_name='รถที่จอง'),
        ),
    ]
