# Generated by Django 5.2.5 on 2025-11-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_usercar_booking_user_car'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parking Booking', 'verbose_name_plural': 'Parking Bookings'},
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['zone', 'spot_number'], 'verbose_name': 'Parking Spot', 'verbose_name_plural': 'Parking Spots'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Parking Ticket', 'verbose_name_plural': 'Parking Tickets'},
        ),
        migrations.AlterModelOptions(
            name='usercar',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'User Car', 'verbose_name_plural': 'User Cars'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_license',
            field=models.CharField(max_length=20, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_model',
            field=models.CharField(max_length=100, verbose_name='Brand/Model'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.parkingspot', verbose_name='Parking Spot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Booked By'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.usercar', verbose_name='Selected Car'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Spot Number'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='zone',
            field=models.CharField(choices=[('A', 'Zone A - Near Entrance'), ('B', 'Zone B - Middle Area'), ('C', 'Zone C - Back Area')], max_length=1, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Issued At'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ticket Number'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Car Color'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='car_license',
            field=models.CharField(max_length=20, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='car_model',
            field=models.CharField(max_length=100, verbose_name='Brand/Model'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Car'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
